---
- name: Install yay
  command: 
    cmd: sudo pacman -S --needed git base-devel --noconfirm

- name: Make sure yay-bin is not present
  ansible.builtin.file:
    path: yay-bin
    state: absent

- name: clone yay
  command: 
    cmd: git clone https://aur.archlinux.org/yay-bin.git

- name: makepkg
  when: lookup('env', 'USER') == "root"
  command: 
    cmd: sudo -u admin makepkg -si --noconfirm
    chdir: yay-bin

- name: makepkg
  when: lookup('env', 'USER') != "root"
  command: 
    cmd: makepkg -si --noconfirm
    chdir: yay-bin

- name: Make sure yay-bin is not present
  ansible.builtin.file:
    path: yay-bin
    state: absent

