---
- name: Install package prometheus-node-exporter from repo
  become: yes
  community.general.pacman:
    name: prometheus-node-exporter
    state: present
    update_cache: yes

- name: create node-exporter service for consul
  become: yes
  copy:
    force: yes
    owner: consul
    group: consul
    dest: /etc/consul.d/node-exporter.json
    content: |
      {
        "service":
          {
            "id": "node-exporter",
            "name": "node-exporter",
            "port": 9100,
            "address":"",
            "checks": [
              {
                "id": "node-exporter-health",
                "name": "node-exporter health check",
                "http": "http://localhost:9100/health",
                "method": "GET",
                "interval": "30s"
              }
            ]
          }
      }

- name: reload consul
  command: consul reload

- name: ufw allow consul tcp ports
  become: yes
  ufw:
    rule: allow
    interface: wg0
    direction: in
    proto: tcp
    to_port: "9100"

- name: Make sure prometheus-node-exporter is running
  become: yes
  ansible.builtin.systemd:
    state: restarted
    name: prometheus-node-exporter
    enabled: yes