---
- name: Set hostname to "{{ inventory_hostname }}"
  become: yes
  command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Install package promtail from repo
  become: yes
  community.general.pacman:
    name: promtail
    state: present
    update_cache: yes

- name: allow promtail access to systemd
  become: yes
  ansible.builtin.user:
    name: promtail
    groups: adm,promtail
    append: yes

- name: add promtail config
  become: yes
  copy:
    force: yes
    owner: promtail
    group: promtail
    dest: /etc/loki/promtail.yaml
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      clients:
        - url: http://loki.service.home:3100/loki/api/v1/push
      scrape_configs:
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /run/log/journal
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'
        pipeline_stages:
        - regex:
            expression: '^\[(?P<app>[^ ]+) (?P<method>[^ ]+)] IN=(?P<IN>.+)OUT=(?P<OUT>.+)(MAC=(?P<MAC>[\S]+))* SRC=(?P<SRC>[\S]+) DST=(?P<DST>[\S]+).*PROTO=(?P<PROTO>[\S]+) SPT=(?P<SPT>[\S]+) DPT=(?P<DPT>[\S]+)'
        - labels:
            app:
            method:

- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/promtail.service.d
    state: directory
    owner: root
    group: root

- name: create promtail system service drop-in
  become: yes
  copy:
    force: yes
    mode: 0644
    owner: root
    group: root
    dest: /etc/systemd/system/promtail.service.d/drop-in.conf
    content: |
      [Service]
      MemoryMax=80M

- name: set consul systemd timer service
  become: yes
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/promtail.timer
    content: |
      [Unit]
      Description=Start promtail 10 mins after boot

      [Timer]
      OnBootSec=10min

      [Install]
      WantedBy=timers.target

- name: Make sure promtail is running
  become: yes
  ansible.builtin.systemd:
    state: restarted
    name: promtail.timer
    enabled: yes

- name: create consul entry
  become: yes
  copy:
    force: yes
    owner: consul
    group: consul
    dest: /etc/consul.d/promtail.json
    content: |
      {
        "service":
          {
            "id": "promtail",
            "name": "promtail",
            "port": 9080,
            "address":"",
            "checks": [
              {
                "id": "promtail-health",
                "name": "promtail health check",
                "http": "http://localhost:9080/ready",
                "method": "GET",
                "interval": "30s"
              }
            ]
          }
        }     

- name: reload consul
  command: consul reload

- name: enable journald volatile storage to reduce k3s load on the disk
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    insertafter: '^[Journal]'
    regexp: '^Storage='
    line: Storage=volatile

- name: enable journald volatile storage to reduce k3s load on the disk
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#Storage'
    state: absent

- name: Reload systemd-journal
  become: yes
  ansible.builtin.systemd:
    name: systemd-journald
    daemon_reload: yes
    state: restarted