---
- name: Populate service facts
  service_facts:
### get mounted swap
- name: Show where swap is mounted
  shell: swapon -s | awk 'NR==2{print $1}'
  register: swap
  tags: [ swap ]
      
# AZURE SWAP
# enable swap on azure vms through walinuxagent if there is no swap yet
# https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/oom-swap-file-linux-vm#resolution
- include: enable-swap-azure.yml
  when: swap.stdout | length == 0 and (ansible_facts.services['waagent.service'] is defined or ansible_facts.services['walinuxagent.service'] is defined)
  tags: [ swap ]
# TODO: NORMAL SWAP for BTRFS
# - name: operatingsystem_app_services
#   set_fact:
#     swapfile_location: "/"
#   when: ansible_facts['os_family'] == "Debian"
#   tags: [ swap ]
# - name: operatingsystem_app_services
#   set_fact:
#     swapfile_location: "/var/lib/swap/"
#   when: ansible_facts['os_family'] == "Suse"
#   tags: [ swap ]
# # use normal swapfile on ubuntu if there is no swap yet and no walinuxagent
# - include: enable-swap.yml
#   when: swap.stdout | length == 0 and ansible_facts.services['walinuxagent.service'] is not defined
#   tags: [ swap ]