plugin: azure_rm
include_vm_resource_groups:
  - tf-connectivity
  - tf-vms
auth_source: auto
conditional_groups:
  azure: true
default_host_filters:
  - "provisioning_state != \"succeeded\""
keyed_groups:
 - key: tags.applicationRole
 - key: powerstate