plugin: azure_rm
include_vm_resource_groups:
  - tf-connectivity
  - tf-k3s
auth_source: auto
conditional_groups:
  linux: "image.offer is defined and 'CentOS' in image.offer"
  windows: "image.offer is defined and 'WindowsServer' in image.offer"
  azure: true
default_host_filters:
  - "provisioning_state != \"succeeded\""
keyed_groups:
 - key: tags.applicationRole
 - key: powerstate