---
- name: Download onboarding agent config
  get_url:
    url: https://aka.ms/azcmagent
    dest: ./install_linux_azcmagent.sh

- name: Run onboarding script
  command: bash install_linux_azcmagent.sh

- name: Connect azcmagent
  command: | 
    sudo azcmagent connect \
    --service-principal-id "{{ azure_arc_linux.servicePrincipalClientId }}" \
    --service-principal-secret "{{ azure_arc_linux.servicePrincipalSecret }}" \
    --resource-group "{{ azure_arc_linux.resource_group }}" \
    --tenant-id "{{ azure_arc_linux.tenant_id }}" \
    --location "{{ azure_arc_linux.location }}" \
    --subscription-id "{{ azure_arc_linux.subscription_id }}" \
    --cloud "AzureCloud" \
    --correlation-id "{{ azure_arc_linux.correlation_id }}"