---
- name: install azure cli
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  args:
    warn: no

- name: add connectedk8s extension
  shell: az extension add --upgrade -n connectedk8s
  args:
    warn: no