---
- name: Install k3s-bin
  command: yay -S k3s-bin --noconfirm
  args:
    warn: no

- name: Set hostname to "{{ inventory_hostname }}"
  become: yes
  command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Get the k3s token
  ignore_errors: true
  become: yes
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  delegate_to: "{{ groups._k3s_server[0] }}"

- name: Set k3s server url
  set_fact:
    k3s_server_url: 'https://{{ hostvars[groups._k3s_server[0]].tags.wireguard_ip.split("/")[0] }}:6443'

- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: edit k3s systemd service for initial server
  become: yes
  when: "'_k3s_server' in group_names and k3s_token['content'] is not defined"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Unit]
      After=wg-quick@wg0.service
      After=iptables.service

      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s server --cluster-init --snapshotter=native --advertise-address {{ hostvars[inventory_hostname]['tags']['wireguard_ip'].split("/")[0] }} --flannel-iface=wg0 --node-taint node-role.kubernetes.io/master=true:NoSchedule

- name: edit k3s systemd service for server
  become: yes
  when: "'_k3s_server' in group_names and k3s_token['content'] is defined"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Unit]
      After=wg-quick@wg0.service
      After=iptables.service

      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s server --server {{ k3s_server_url }} --snapshotter=native --token {{ k3s_token['content'] | b64decode | trim }} --advertise-address {{ hostvars[inventory_hostname]['tags']['wireguard_ip'].split("/")[0] }} --flannel-iface=wg0 --node-taint node-role.kubernetes.io/master=true:NoSchedule

- name: edit k3s systemd service for agent
  become: yes
  when: "'_k3s_agent' in group_names"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Unit]
      After=wg-quick@wg0.service
      After=iptables.service

      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s agent --snapshotter=native --server {{ k3s_server_url }} --token {{ k3s_token['content'] | b64decode | trim }} --flannel-iface=wg0

- name: Allow SSH on iptables
  ansible.builtin.iptables:
    in_interface: eth0
    protocol: tcp
    limit: 5/s
    destination_port: 22
    jump: ACCEPT
    chain: INPUT
  become: yes

- name: Allow Wireguard on iptables
  ansible.builtin.iptables:
    in_interface: eth0
    destination_port: 51820
    protocol: udp
    jump: ACCEPT
    chain: INPUT
  become: yes

- name: Allow related and established connections
  ansible.builtin.iptables:
    in_interface: eth0
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Deny all tcp on eth0 on iptables
  ansible.builtin.iptables:
    in_interface: eth0
    protocol: tcp
    jump: DROP
    chain: INPUT
  become: yes

- name: Deny all udp on eth0 on iptables
  ansible.builtin.iptables:
    in_interface: eth0
    protocol: udp
    jump: DROP
    chain: INPUT
  become: yes

- name: Save current state of iptables in system file
  become: yes
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/iptables.rules

- name: Start and enable iptables
  become: yes
  ansible.builtin.systemd:
    name: iptables
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: Reload service k3s
  become: yes
  ansible.builtin.systemd:
    name: k3s
    enabled: yes
    daemon_reload: yes
    state: restarted