---
- name: Install k3s-bin
  command: yay -S k3s-bin --noconfirm
  args:
    warn: no

- name: Set hostname to "{{ inventory_hostname }}"
  become: yes
  command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Get the k3s token
  become: yes
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  delegate_to: "{{ groups._k3s_server[0] }}"

- name: Set k3s server url
  set_fact:
    k3s_server_url: "https://{{ hostvars[groups._k3s_server[0]].tags.wireguard_ip }}:6443"

- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: edit k3s systemd service for server
  become: yes
  when: "'_k3s_server' in group_names"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s server --server {{ k3s_server_url }} --snapshotter=native --token {{ k3s_token['content'] | b64decode | trim }} --advertise-address {{ hostvars[inventory_hostname]['tags']['wireguard_ip'] }} --flannel-iface=wg0 --node-taint node-role.kubernetes.io/master=true:NoSchedule

- name: edit k3s systemd service for agent
  become: yes
  when: "'_k3s_agent' in group_names"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Unit]
      After=wg-quick@wg0.service

      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s agent --snapshotter=native --server {{ k3s_server_url }} --token {{ k3s_token['content'] | b64decode | trim }} --flannel-iface=wg0

- name: set kubernetes ports
  set_fact:
    k3s_ports:
      - 80
      - 443
      - 2379:2380
      - 4789
      - 6443
      - 8443
      - 8472
      - 9099
      - 9100
      - 9443
      - 9796
      - 10250
      - 10254
      - 30000:65535
    flannel_ports:
      - 8285
      - 8472
      - 30000:65535

- name: ufw allow k3s ports
  become: yes
  ufw:
    rule: allow
    interface: wg0
    direction: in
    port: "{{ item }}"
    proto: tcp
  loop: "{{ k3s_ports }}"

- name: ufw allow k3s flannel ports
  become: yes
  ufw:
    rule: allow
    interface: wg0
    direction: in
    port: "{{ item }}"
    proto: udp
  loop: "{{ flannel_ports }}"

- name: ufw allow k3s flannel ports
  become: yes
  ufw:
    rule: allow
    interface: cni0
    direction: in
    proto: udp
  loop: "{{ flannel_ports }}"

- name: allow routed for flannel
  become: yes
  ufw:
    rule: allow
    route: yes

- name: Reload service k3s
  become: yes
  ansible.builtin.systemd:
    name: k3s
    no_block: yes
    enabled: yes
    daemon_reload: yes
    state: restarted