---
- name: Install k3s-bin
  command: yay -S k3s-bin --noconfirm
  args:
    warn: no

- name: Set hostname to "{{ inventory_hostname }}"
  become: yes
  command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Get the k3s token
  ignore_errors: true
  become: yes
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  delegate_to: "{{ groups._k3s_server[0] }}"

- name: Set k3s server url
  set_fact:
    k3s_server_url: "https://{{ hostvars[groups._k3s_server[0]].tags.wireguard_ip }}:6443"

- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: edit k3s systemd service for server
  become: yes
  when: "'_k3s_server' in group_names"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s server --server --snapshotter=native --advertise-address {{ hostvars[inventory_hostname]['tags']['wireguard_ip'].split("/")[0] }} --flannel-iface=wg0 --node-taint node-role.kubernetes.io/master=true:NoSchedule

- name: edit k3s systemd service for agent
  become: yes
  when: "'_k3s_agent' in group_names"
  copy:
    mode: 0644
    owner: root
    group: root
    force: yes
    dest: /etc/systemd/system/k3s.service.d/network.conf
    content: |
      [Unit]
      After=wg-quick@wg0.service

      [Service]
      ExecStart=
      ExecStart=/usr/bin/k3s agent --snapshotter=native --server {{ k3s_server_url }} --token {{ k3s_token['content'] | b64decode | trim }} --flannel-iface=wg0

- name: disable ufw for k3s
  when: "'systemd' in process_one['stdout']"
  become: yes
  ufw:
    state: disabled
    policy: deny

- name: Make sure ufw is disabled
  become: yes
  when: "'systemd' in process_one['stdout']"
  ansible.builtin.systemd:
    state: stopped
    name: ufw
    enabled: no

- name: Reload service k3s
  become: yes
  ansible.builtin.systemd:
    name: k3s
    no_block: yes
    enabled: yes
    daemon_reload: yes
    state: restarted