---
- name: Unarchive a file that needs to be downloaded
  become: yes
  unarchive:
    src: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_{{ go_arch }}.tgz"
    dest: /usr/local/bin/
    remote_src: yes

- name: Create the coredns group
  become: yes
  group:
    name: "{{ coredns_system_group }}"
    state: present
    system: true

- name: Create the coredns user
  become: yes
  user:
    name: "{{ coredns_system_user }}"
    groups: "{{ coredns_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: create coredns configuration directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/coredns
    - /etc/coredns/zones

- name: Copy the coredns systemd service file
  become: yes
  copy:
    mode: 0644
    force: yes
    dest: /etc/systemd/system/coredns.service
    content: |
      [Unit]
      Description=CoreDNS
      Documentation=https://coredns.io
      After=network.target
      Wants=nss-lookup.target
      Before=nss-lookup.target
      StartLimitInterval=0
      [Service]
      Type=simple
      PermissionsStartOnly=true
      LimitNOFILE=1048576
      LimitNPROC=512
      CapabilityBoundingSet=CAP_NET_BIND_SERVICE
      AmbientCapabilities=CAP_NET_BIND_SERVICE
      NoNewPrivileges=true
      WorkingDirectory=/etc/coredns
      User={{ coredns_system_user }}
      Group={{ coredns_system_group }}
      ExecStart=/usr/local/bin/coredns \
          -conf /etc/coredns/Corefile \
          -dns.port "{{ coredns_dns_port }}"
      SyslogIdentifier=coredns
      ExecReload=/bin/kill -SIGUSR1 $MAINPID
      Restart=always
      RestartSec=0
      [Install]
      WantedBy=multi-user.target      

- name: Create symbolic link required for dns
  become: yes
  file:
    force: yes
    src: "/run/resolvconf/resolv.conf"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    state: link