---
- name: Setup Archlinux
  hosts: all
  roles:
  - yay
  - k3s
  - azure-cli
  vars_prompt:
    - name: username
      prompt: "Enter username for ssh"
      private: no
    - name: password
      prompt: "Enter password for ssh"
  vars:
    ansible_connection: ssh
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"