- name: configure devops machine
  hosts: _devops
  roles:
  - role: ansible-modules-bitwarden
    tags: [ always ]
  - role: prometheus
    tags: [ prometheus ]
  - role: grafana
    tags: [ grafana ]
  - role: loki
    tags: [ loki ]
  - role: drone
    tags: [ drone ]