- name: configure wireguard peers
  hosts: all:!_wireguard
  roles:
  - role: wireguard
    tags: [ wireguard ]
  - role: yay
    tags: [ yay ]
  - role: unbound
    tags: [ unbound]
  - role: consul
    consul_role: client
    tags: [ consul ]
  - role: node-exporter
    tags: [ node-exporter ]
  - role: promtail
    tags: [ promtail ]
  - role: restic
    tags: [ restic ]

- name: configure wireguard server
  hosts: _wireguard
  roles:
  - role: wireguard
    tags: [ wireguard ]
  - role: yay
    tags: [ yay ]
  - role: consul
    consul_role: server
    tags: [ consul ]
  - role: coredns
    tags: [ coredns ]
  - role: node-exporter
    tags: [ node-exporter ]
  - role: promtail
    tags: [ promtail ]
  - role: restic
    tags: [ restic ]
  - role: rclone
    tags: [ rclone ]
  - role: nginx
    tags: [ nginx ]