- name: configure wireguard peers
  hosts: all:!_wireguard
  roles:
  - role: ansible-modules-bitwarden
    tags: [ always ]
  - role: wireguard
    tags: [ wireguard ]
  - role: consul
    consul_role: client
    tags: [ consul ]
  - role: node-exporter
    tags: [ node-exporter ]
  - role: swap
    tags: [ swap ]
  - role: promtail
    tags: [ promtail ]
  - role: restic
    tags: [ restic ]

- name: configure wireguard server
  hosts: _wireguard
  roles:
  - role: ansible-modules-bitwarden
    tags: [ always ]
  - role: wireguard
    tags: [ wireguard ]
  - role: coredns
    tags: [ coredns ]
  - role: consul
    consul_role: server
    tags: [ consul ]
  - role: node-exporter
    tags: [ node-exporter ]
  - role: swap
    tags: [ swap ]
  - role: promtail
    tags: [ promtail ]
  - role: restic
    tags: [ restic ]
  - role: nginx
    tags: [ nginx ]