- name: configure wireguard peers
  hosts: all:!_wireguard
  roles:
  - role: ansible-modules-bitwarden
    tags: [ always ]
  - role: wireguard
    tags: [ wireguard ]

- name: configure wireguard server
  hosts: _wireguard
  roles:
  - role: ansible-modules-bitwarden
    tags: [ always ]
  - role: wireguard
    tags: [ wireguard ]
  - role: coredns
    tags: [ coredns ]
