---
- name: Update repositories cache and install "wireguard" package
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt:
    name: wireguard
    update_cache: yes

- name: install wireguard
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  community.general.pacman:
    name: wireguard-tools
    state: present

- name: install ufw
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  community.general.pacman:
    name: ufw
    state: present

- name: Check if private key exists
  become: yes
  stat:
    path: "/etc/wireguard/privatekey"
  register: privatekey_result

- name: Generate public key
  when: not privatekey_result.stat.exists
  become: yes
  shell: wg genkey > /etc/wireguard/privatekey

- name: Check if public key exists
  become: yes
  stat:
    path: "/etc/wireguard/publickey"
  register: publickey_result

- name: Generate public key
  when: not publickey_result.stat.exists
  become: yes
  shell: wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey

- name: Get the private key
  become: yes
  ansible.builtin.slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_server_privatekey

- name: ensure wg0 file exists
  become: yes
  copy:
    content: ""
    dest: "/etc/wireguard/wg0.conf"
    force: no
    group: root
    owner: root

- name: Creating wireguard config
  become: yes
  blockinfile:
    dest: "/etc/wireguard/wg0.conf"
    insertafter: BOF
    state: present
    marker: "# ANSIBLE MANAGED {{ inventory_hostname }} WG PEER"
    dest: "/etc/wireguard/wg0.conf"
    block: |
      [Interface]
      Address = {{ hostvars[inventory_hostname].tags.wireguard_ip }}
      PrivateKey = {{ wireguard_server_privatekey['content'] | b64decode }}
      ListenPort = 51820
      PostUp = ufw route allow in on wg0 out on {{ ansible_default_ipv4.interface }}
      PostUp = iptables -t nat -I POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE
      PostUp = ip6tables -t nat -I POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE
      PreDown = ufw route delete allow in on wg0 out on {{ ansible_default_ipv4.interface }}
      PreDown = iptables -t nat -D POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE
      PreDown = ip6tables -t nat -D POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE

- name: add wireguard server as peer
  when: "not '_wireguard' in group_names"
  become: yes
  blockinfile:
    dest: "/etc/wireguard/wg0.conf"
    insertafter: BOF
    state: present
    marker: "# ANSIBLE MANAGED {{ inventory_hostname }} WG PEER"
    block: |
      [Peer]
      PublicKey = {{ wireguard_server_publickey }}
      Endpoint = {{ wireguard_server_endpoint }}
      AllowedIPs = {{ wireguard_vnet_cidr }} {{ ', {0}'.format(remote_vnet_cidr) if not (remote_vnet_cidr | ansible.netcommon.network_in_usable(hostvars[inventory_hostname]['private_ipv4_addresses'][0] | default(hostvars[inventory_hostname].ansible_host))) else '' }}
      {% if not subnet | ansible.netcommon.network_in_usable(hostvars[inventory_hostname]['private_ipv4_addresses'][0] | default(hostvars[inventory_hostname].ansible_host)) %}
      # For NAT to allow incoming traffic
      PersistentKeepalive = 25
      {% endif %}

- name: Get the public key from peers
  become: yes
  ansible.builtin.slurp:
    src: /etc/wireguard/publickey
  register: publickeys
  loop: "{{ groups._running |difference([inventory_hostname]) }}"
  delegate_to: "{{ item }}"

- name: get subnet from netmask
  set_fact:
    subnet: "{{ (ansible_default_ipv4.address + '/255.255.255.0') | ansible.netcommon.ipaddr('network/prefix') }}"

- name: add wireguard peers for mesh
  when: "not '_wireguard' in group_names"
  become: yes
  blockinfile:
    dest: "/etc/wireguard/wg0.conf"
    insertafter: BOF
    state: present
    marker: "# ANSIBLE MANAGED WG {{ item['item'] }} PEER"
    block: |
      {% if subnet | ansible.netcommon.network_in_usable(hostvars[item['item']]['private_ipv4_addresses'][0] | default(hostvars[item['item']].ansible_host)) %}
      [Peer]
      AllowedIPs = {{ hostvars[item['item']].tags.wireguard_ip }}
      PublicKey = {{ item['content'] | b64decode }}
      Endpoint = {{ hostvars[item['item']]['private_ipv4_addresses'][0] | default(hostvars[item['item']].ansible_host) }}:51820
      {% endif %}
  loop: "{{ publickeys['results'] }}"

- name: add wireguard peers to server
  when: '"_wireguard" in group_names'
  become: yes
  blockinfile:
    dest: "/etc/wireguard/wg0.conf"
    insertafter: BOF
    state: present
    marker: "# ANSIBLE MANAGED WG {{ item['item'] }}  PEER"
    block: |
      [Peer]
      AllowedIPs = {{ hostvars[item['item']].tags.wireguard_ip }}
      PublicKey = {{ item['content'] | b64decode }}
      {% if (hostvars[item['item']]['private_ipv4_addresses'][0] | default(hostvars[item['item']].ansible_host)) | ipaddr(subnet) | ipaddr('bool') %}
      Endpoint = {{ hostvars[item['item']]['private_ipv4_addresses'][0] | default(hostvars[item['item']].ansible_host) }}:51820
      {% endif %}
  loop: "{{ publickeys['results'] }}"

- name: add mobile peers to server
  when: '"_wireguard" in group_names'
  become: yes
  blockinfile:
    dest: "/etc/wireguard/wg0.conf"
    insertafter: BOF
    state: present
    marker: "# mobile1 ANSIBLE MANAGED WG PEER"
    block: |
      [Peer]
      AllowedIPs = {{ wireguard_mobile_ip }}
      PublicKey = {{ wireguard_mobile_publickey }}

- name: allow ip forward
  become: yes
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Make sure wireguard is running
  become: yes
  ansible.builtin.systemd:
    state: started
    name: wg-quick@wg0
    enabled: yes

- name: Sync wg conf
  become: yes
  shell: wg syncconf wg0 <(wg-quick strip wg0)
  args:
    warn: no 

- name: limit ssh on ufw
  become: yes
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: ufw allow wireguard
  become: yes
  ufw:
    rule: allow
    port: 51820
    proto: udp

- name: enable ufw
  become: yes
  ufw:
    state: enabled
    policy: deny

- name: allow forwarding from eth0 to wg on server
  when: '"wireguard" in group_names'
  become: yes
  ufw:
    rule: allow
    route: yes

- name: Make sure ufw is enabled
  become: yes
  ansible.builtin.systemd:
    state: started
    name: ufw
    enabled: yes